/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package basketballpractice.view.form;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;

/**
 * Glavna serverska forma
 * @author Aleksandar
 */
public class FrmMain extends javax.swing.JFrame {

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbStudent = new javax.swing.JLabel();
        btnStart = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        jlbProgramName = new javax.swing.JLabel();
        jmbMain = new javax.swing.JMenuBar();
        jmServer = new javax.swing.JMenu();
        jmiSettings = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlbStudent.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbStudent.setText("Aleksandar Bursac 2017/0089");

        btnStart.setText("Start Server");

        btnStop.setText("Stop Server");

        jlbProgramName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbProgramName.setText("Basketball Practice Manager");

        jmServer.setText("Server");

        jmiSettings.setText("Settings");
        jmiSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSettingsActionPerformed(evt);
            }
        });
        jmServer.add(jmiSettings);

        jmbMain.add(jmServer);

        setJMenuBar(jmbMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbStudent)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnStart)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnStop))
                    .addComponent(jlbProgramName))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbProgramName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbStudent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnStop, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSettingsActionPerformed
    }//GEN-LAST:event_jmiSettingsActionPerformed

    /**
     * Getter za button Start
     * @return 
     */

    public JButton getBtnStart() {
        return btnStart;
    }

    /**
     * Getter za button Stop
     * @return
     */
    public JButton getBtnStop() {
        return btnStop;
    }

    /**
     * Getter za jlbProgramName
     * @return
     */
    public JLabel getJlbProgramName() {
        return jlbProgramName;
    }

    /**
     * Getter za jlbStudent
     * @return
     */
    public JLabel getJlbStudent() {
        return jlbStudent;
    }

    /**
     * Getter za jmServer
     * @return
     */
    public JMenu getJmServer() {
        return jmServer;
    }

    /**
     * Getter za jmbMain
     * @return
     */
    public JMenuBar getJmbMain() {
        return jmbMain;
    }

    

    /**
     * Getter za jmiSettings
     * @return 
     */
    public JMenuItem getJmiSettings() {
        return jmiSettings;
    }

    /**
     * Postavlja listener na button Start
     * @param actionListener
     */
    public void AddBtnStartActionListener(ActionListener actionListener) {
        btnStart.addActionListener(actionListener);
    }
    
    /**
     * Postavlja listener na button Stop
     * @param actionListener
     */
    public void AddBtnStopActionListener(ActionListener actionListener) {
        btnStop.addActionListener(actionListener);
    }
    
    /**
     * Postavlja listener na jmiSettings
     * @param actionListener
     */
    public void AddJmiSettingsActionListener(ActionListener actionListener) {
        jmiSettings.addActionListener(actionListener);
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnStop;
    private javax.swing.JLabel jlbProgramName;
    private javax.swing.JLabel jlbStudent;
    private javax.swing.JMenu jmServer;
    private javax.swing.JMenuBar jmbMain;
    private javax.swing.JMenuItem jmiSettings;
    // End of variables declaration//GEN-END:variables
}
